device: cuda
pin_memory: true
T: 350
lr: 1.0e-06
loss_fn: l2
batch_size: 8
accumulate_grad_batches: 4
img_size: 224
sample: true
should_log: true
epochs: 5
using_cond: true
display_every: 350
dynamic_threshold: false
train_autoenc: false
enc_loss_coeff: 1.1
